// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXq3Onq3DdeezqwvJc4O9tve9LrcSJwn8',
    appId: '1:58602674723:web:5d62052a048254e8ca2f96',
    messagingSenderId: '58602674723',
    projectId: 'note-project-3d70d',
    authDomain: 'note-project-3d70d.firebaseapp.com',
    storageBucket: 'note-project-3d70d.appspot.com',
    measurementId: 'G-5YB7H6ZCCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJo9QTO0oKIHLiGGPUdleqgdIY4pScIio',
    appId: '1:58602674723:android:2d21ca5df582b3ccca2f96',
    messagingSenderId: '58602674723',
    projectId: 'note-project-3d70d',
    storageBucket: 'note-project-3d70d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXGnUf4otMkx4iR-ZbEHzSmbuiGXoc1oI',
    appId: '1:58602674723:ios:78e2256c116873caca2f96',
    messagingSenderId: '58602674723',
    projectId: 'note-project-3d70d',
    storageBucket: 'note-project-3d70d.appspot.com',
    iosBundleId: 'com.example.aplicativoNotas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXGnUf4otMkx4iR-ZbEHzSmbuiGXoc1oI',
    appId: '1:58602674723:ios:78e2256c116873caca2f96',
    messagingSenderId: '58602674723',
    projectId: 'note-project-3d70d',
    storageBucket: 'note-project-3d70d.appspot.com',
    iosBundleId: 'com.example.aplicativoNotas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXq3Onq3DdeezqwvJc4O9tve9LrcSJwn8',
    appId: '1:58602674723:web:5dcff8ed45dbfdd5ca2f96',
    messagingSenderId: '58602674723',
    projectId: 'note-project-3d70d',
    authDomain: 'note-project-3d70d.firebaseapp.com',
    storageBucket: 'note-project-3d70d.appspot.com',
    measurementId: 'G-1FE0SCLXEF',
  );

}